# Generated by Django 2.1.1 on 2018-11-19 14:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'db_table': 'Category',
                'ordering': ('title',),
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('description', models.TextField(default='Описание отсутствует', verbose_name='Описание')),
                ('in_stock', models.BooleanField(verbose_name='В наличии')),
                ('thumbnail_with', models.PositiveIntegerField()),
                ('thumbnail_height', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(height_field=models.PositiveIntegerField(), upload_to='products/thumbnails', width_field=models.PositiveIntegerField())),
                ('category', models.ForeignKey(on_delete='CASCADE', to='Army.Category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'Product ',
                'ordering': ('title',),
            },
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
