# Generated by Django 2.1.1 on 2018-10-03 07:26

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0003_category_description'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
