# Generated by Django 2.1.1 on 2018-10-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0005_auto_20181003_2035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('description', models.TextField()),
                ('in_stock', models.BooleanField()),
                ('category', models.ForeignKey(on_delete='CASCADE', to='LearnModels.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'db_table': 'Product',
                'ordering': ('id',),
            },
        ),
    ]
