# Generated by Django 2.1.1 on 2018-10-07 07:58

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('LearnModels', '0007_auto_20181003_2055'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('obj', django.db.models.manager.Manager()),
            ],
        ),
    ]
